# Generated by Django 3.2.24 on 2024-02-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20240220_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparationTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(null=True),
        ),
    ]
