# Generated by Django 3.2.24 on 2024-02-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_recipe_foodart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='foodart',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
