# Generated by Django 3.2.24 on 2024-02-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20240222_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='foodart',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
